// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.19.6
// source: receptor_logs.proto

package logger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity levels based on OpenTelemetry log severity spec
type SeverityNumber int32

const (
	SeverityNumber_SEVERITY_UNSPECIFIED SeverityNumber = 0
	SeverityNumber_SEVERITY_TRACE       SeverityNumber = 1
	SeverityNumber_SEVERITY_TRACE2      SeverityNumber = 2
	SeverityNumber_SEVERITY_TRACE3      SeverityNumber = 3
	SeverityNumber_SEVERITY_TRACE4      SeverityNumber = 4
	SeverityNumber_SEVERITY_DEBUG       SeverityNumber = 5
	SeverityNumber_SEVERITY_DEBUG2      SeverityNumber = 6
	SeverityNumber_SEVERITY_DEBUG3      SeverityNumber = 7
	SeverityNumber_SEVERITY_DEBUG4      SeverityNumber = 8
	SeverityNumber_SEVERITY_INFO        SeverityNumber = 9
	SeverityNumber_SEVERITY_INFO2       SeverityNumber = 10
	SeverityNumber_SEVERITY_INFO3       SeverityNumber = 11
	SeverityNumber_SEVERITY_INFO4       SeverityNumber = 12
	SeverityNumber_SEVERITY_WARN        SeverityNumber = 13
	SeverityNumber_SEVERITY_WARN2       SeverityNumber = 14
	SeverityNumber_SEVERITY_WARN3       SeverityNumber = 15
	SeverityNumber_SEVERITY_WARN4       SeverityNumber = 16
	SeverityNumber_SEVERITY_ERROR       SeverityNumber = 17
	SeverityNumber_SEVERITY_ERROR2      SeverityNumber = 18
	SeverityNumber_SEVERITY_ERROR3      SeverityNumber = 19
	SeverityNumber_SEVERITY_ERROR4      SeverityNumber = 20
	SeverityNumber_SEVERITY_FATAL       SeverityNumber = 21
	SeverityNumber_SEVERITY_FATAL2      SeverityNumber = 22
	SeverityNumber_SEVERITY_FATAL3      SeverityNumber = 23
	SeverityNumber_SEVERITY_FATAL4      SeverityNumber = 24
)

// Enum value maps for SeverityNumber.
var (
	SeverityNumber_name = map[int32]string{
		0:  "SEVERITY_UNSPECIFIED",
		1:  "SEVERITY_TRACE",
		2:  "SEVERITY_TRACE2",
		3:  "SEVERITY_TRACE3",
		4:  "SEVERITY_TRACE4",
		5:  "SEVERITY_DEBUG",
		6:  "SEVERITY_DEBUG2",
		7:  "SEVERITY_DEBUG3",
		8:  "SEVERITY_DEBUG4",
		9:  "SEVERITY_INFO",
		10: "SEVERITY_INFO2",
		11: "SEVERITY_INFO3",
		12: "SEVERITY_INFO4",
		13: "SEVERITY_WARN",
		14: "SEVERITY_WARN2",
		15: "SEVERITY_WARN3",
		16: "SEVERITY_WARN4",
		17: "SEVERITY_ERROR",
		18: "SEVERITY_ERROR2",
		19: "SEVERITY_ERROR3",
		20: "SEVERITY_ERROR4",
		21: "SEVERITY_FATAL",
		22: "SEVERITY_FATAL2",
		23: "SEVERITY_FATAL3",
		24: "SEVERITY_FATAL4",
	}
	SeverityNumber_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_TRACE":       1,
		"SEVERITY_TRACE2":      2,
		"SEVERITY_TRACE3":      3,
		"SEVERITY_TRACE4":      4,
		"SEVERITY_DEBUG":       5,
		"SEVERITY_DEBUG2":      6,
		"SEVERITY_DEBUG3":      7,
		"SEVERITY_DEBUG4":      8,
		"SEVERITY_INFO":        9,
		"SEVERITY_INFO2":       10,
		"SEVERITY_INFO3":       11,
		"SEVERITY_INFO4":       12,
		"SEVERITY_WARN":        13,
		"SEVERITY_WARN2":       14,
		"SEVERITY_WARN3":       15,
		"SEVERITY_WARN4":       16,
		"SEVERITY_ERROR":       17,
		"SEVERITY_ERROR2":      18,
		"SEVERITY_ERROR3":      19,
		"SEVERITY_ERROR4":      20,
		"SEVERITY_FATAL":       21,
		"SEVERITY_FATAL2":      22,
		"SEVERITY_FATAL3":      23,
		"SEVERITY_FATAL4":      24,
	}
)

func (x SeverityNumber) Enum() *SeverityNumber {
	p := new(SeverityNumber)
	*p = x
	return p
}

func (x SeverityNumber) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SeverityNumber) Descriptor() protoreflect.EnumDescriptor {
	return file_receptor_logs_proto_enumTypes[0].Descriptor()
}

func (SeverityNumber) Type() protoreflect.EnumType {
	return &file_receptor_logs_proto_enumTypes[0]
}

func (x SeverityNumber) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SeverityNumber.Descriptor instead.
func (SeverityNumber) EnumDescriptor() ([]byte, []int) {
	return file_receptor_logs_proto_rawDescGZIP(), []int{0}
}

type WorkloadStatus int32

const (
	WorkloadStatus_WorkStatePending   WorkloadStatus = 0
	WorkloadStatus_WorkStateRunning   WorkloadStatus = 1
	WorkloadStatus_WorkStateSucceeded WorkloadStatus = 2
	WorkloadStatus_WorkStateFailed    WorkloadStatus = 3
	WorkloadStatus_WorkStateCanceled  WorkloadStatus = 4
	WorkloadStatus_WorkStateReleased  WorkloadStatus = 5
	WorkloadStatus_WorkStateUnknown   WorkloadStatus = 6
)

// Enum value maps for WorkloadStatus.
var (
	WorkloadStatus_name = map[int32]string{
		0: "WorkStatePending",
		1: "WorkStateRunning",
		2: "WorkStateSucceeded",
		3: "WorkStateFailed",
		4: "WorkStateCanceled",
		5: "WorkStateReleased",
		6: "WorkStateUnknown",
	}
	WorkloadStatus_value = map[string]int32{
		"WorkStatePending":   0,
		"WorkStateRunning":   1,
		"WorkStateSucceeded": 2,
		"WorkStateFailed":    3,
		"WorkStateCanceled":  4,
		"WorkStateReleased":  5,
		"WorkStateUnknown":   6,
	}
)

func (x WorkloadStatus) Enum() *WorkloadStatus {
	p := new(WorkloadStatus)
	*p = x
	return p
}

func (x WorkloadStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WorkloadStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_receptor_logs_proto_enumTypes[1].Descriptor()
}

func (WorkloadStatus) Type() protoreflect.EnumType {
	return &file_receptor_logs_proto_enumTypes[1]
}

func (x WorkloadStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WorkloadStatus.Descriptor instead.
func (WorkloadStatus) EnumDescriptor() ([]byte, []int) {
	return file_receptor_logs_proto_rawDescGZIP(), []int{1}
}

// Key-value attributes for custom fields, spans, etc.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_receptor_logs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_receptor_logs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_receptor_logs_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Main log entry message
type ReceptorLogRecord struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TraceId        string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"` // OpenTelemetry trace context
	SpanId         string                 `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	TraceFlags     string                 `protobuf:"bytes,3,opt,name=trace_flags,json=traceFlags,proto3" json:"trace_flags,omitempty"`
	SeverityNumber SeverityNumber         `protobuf:"varint,4,opt,name=severity_number,json=severityNumber,proto3,enum=logger.SeverityNumber" json:"severity_number,omitempty"`
	SeverityText   string                 `protobuf:"bytes,5,opt,name=severity_text,json=severityText,proto3" json:"severity_text,omitempty"`
	TimeUnixNano   *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"time_unix_nano,omitempty"`
	Body           string                 `protobuf:"bytes,7,opt,name=body,proto3" json:"body,omitempty"`             // Main log message
	Attributes     []*KeyValue            `protobuf:"bytes,8,rep,name=attributes,proto3" json:"attributes,omitempty"` // Custom metadata
	// Receptor-specific context
	NodeId        string         `protobuf:"bytes,9,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	PeerId        string         `protobuf:"bytes,10,opt,name=peer_id,json=peerId,proto3" json:"peer_id,omitempty"`
	WorkType      string         `protobuf:"bytes,11,opt,name=work_type,json=workType,proto3" json:"work_type,omitempty"`
	WorkUnitId    string         `protobuf:"bytes,12,opt,name=work_unit_id,json=workUnitId,proto3" json:"work_unit_id,omitempty"`
	ConnectionId  string         `protobuf:"bytes,13,opt,name=connection_id,json=connectionId,proto3" json:"connection_id,omitempty"`
	Namespace     string         `protobuf:"bytes,14,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Subsystem     string         `protobuf:"bytes,15,opt,name=subsystem,proto3" json:"subsystem,omitempty"`
	LoggerName    string         `protobuf:"bytes,16,opt,name=logger_name,json=loggerName,proto3" json:"logger_name,omitempty"`
	TypeId        string         `protobuf:"bytes,17,opt,name=type_id,json=typeId,proto3" json:"type_id,omitempty"` // todo: make enum for hop, control, executor, transport, awxcontroller, ...
	Status        WorkloadStatus `protobuf:"varint,18,opt,name=status,proto3,enum=logger.WorkloadStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReceptorLogRecord) Reset() {
	*x = ReceptorLogRecord{}
	mi := &file_receptor_logs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReceptorLogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceptorLogRecord) ProtoMessage() {}

func (x *ReceptorLogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_receptor_logs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceptorLogRecord.ProtoReflect.Descriptor instead.
func (*ReceptorLogRecord) Descriptor() ([]byte, []int) {
	return file_receptor_logs_proto_rawDescGZIP(), []int{1}
}

func (x *ReceptorLogRecord) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *ReceptorLogRecord) GetSpanId() string {
	if x != nil {
		return x.SpanId
	}
	return ""
}

func (x *ReceptorLogRecord) GetTraceFlags() string {
	if x != nil {
		return x.TraceFlags
	}
	return ""
}

func (x *ReceptorLogRecord) GetSeverityNumber() SeverityNumber {
	if x != nil {
		return x.SeverityNumber
	}
	return SeverityNumber_SEVERITY_UNSPECIFIED
}

func (x *ReceptorLogRecord) GetSeverityText() string {
	if x != nil {
		return x.SeverityText
	}
	return ""
}

func (x *ReceptorLogRecord) GetTimeUnixNano() *timestamppb.Timestamp {
	if x != nil {
		return x.TimeUnixNano
	}
	return nil
}

func (x *ReceptorLogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *ReceptorLogRecord) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ReceptorLogRecord) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ReceptorLogRecord) GetPeerId() string {
	if x != nil {
		return x.PeerId
	}
	return ""
}

func (x *ReceptorLogRecord) GetWorkType() string {
	if x != nil {
		return x.WorkType
	}
	return ""
}

func (x *ReceptorLogRecord) GetWorkUnitId() string {
	if x != nil {
		return x.WorkUnitId
	}
	return ""
}

func (x *ReceptorLogRecord) GetConnectionId() string {
	if x != nil {
		return x.ConnectionId
	}
	return ""
}

func (x *ReceptorLogRecord) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReceptorLogRecord) GetSubsystem() string {
	if x != nil {
		return x.Subsystem
	}
	return ""
}

func (x *ReceptorLogRecord) GetLoggerName() string {
	if x != nil {
		return x.LoggerName
	}
	return ""
}

func (x *ReceptorLogRecord) GetTypeId() string {
	if x != nil {
		return x.TypeId
	}
	return ""
}

func (x *ReceptorLogRecord) GetStatus() WorkloadStatus {
	if x != nil {
		return x.Status
	}
	return WorkloadStatus_WorkStatePending
}

var File_receptor_logs_proto protoreflect.FileDescriptor

const file_receptor_logs_proto_rawDesc = "" +
	"\n" +
	"\x13receptor_logs.proto\x12\x06logger\x1a\x1fgoogle/protobuf/timestamp.proto\"2\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x92\x05\n" +
	"\x11ReceptorLogRecord\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x12\x17\n" +
	"\aspan_id\x18\x02 \x01(\tR\x06spanId\x12\x1f\n" +
	"\vtrace_flags\x18\x03 \x01(\tR\n" +
	"traceFlags\x12?\n" +
	"\x0fseverity_number\x18\x04 \x01(\x0e2\x16.logger.SeverityNumberR\x0eseverityNumber\x12#\n" +
	"\rseverity_text\x18\x05 \x01(\tR\fseverityText\x12@\n" +
	"\x0etime_unix_nano\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\ftimeUnixNano\x12\x12\n" +
	"\x04body\x18\a \x01(\tR\x04body\x120\n" +
	"\n" +
	"attributes\x18\b \x03(\v2\x10.logger.KeyValueR\n" +
	"attributes\x12\x17\n" +
	"\anode_id\x18\t \x01(\tR\x06nodeId\x12\x17\n" +
	"\apeer_id\x18\n" +
	" \x01(\tR\x06peerId\x12\x1b\n" +
	"\twork_type\x18\v \x01(\tR\bworkType\x12 \n" +
	"\fwork_unit_id\x18\f \x01(\tR\n" +
	"workUnitId\x12#\n" +
	"\rconnection_id\x18\r \x01(\tR\fconnectionId\x12\x1c\n" +
	"\tnamespace\x18\x0e \x01(\tR\tnamespace\x12\x1c\n" +
	"\tsubsystem\x18\x0f \x01(\tR\tsubsystem\x12\x1f\n" +
	"\vlogger_name\x18\x10 \x01(\tR\n" +
	"loggerName\x12\x17\n" +
	"\atype_id\x18\x11 \x01(\tR\x06typeId\x12.\n" +
	"\x06status\x18\x12 \x01(\x0e2\x16.logger.WorkloadStatusR\x06status*\x94\x04\n" +
	"\x0eSeverityNumber\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_TRACE\x10\x01\x12\x13\n" +
	"\x0fSEVERITY_TRACE2\x10\x02\x12\x13\n" +
	"\x0fSEVERITY_TRACE3\x10\x03\x12\x13\n" +
	"\x0fSEVERITY_TRACE4\x10\x04\x12\x12\n" +
	"\x0eSEVERITY_DEBUG\x10\x05\x12\x13\n" +
	"\x0fSEVERITY_DEBUG2\x10\x06\x12\x13\n" +
	"\x0fSEVERITY_DEBUG3\x10\a\x12\x13\n" +
	"\x0fSEVERITY_DEBUG4\x10\b\x12\x11\n" +
	"\rSEVERITY_INFO\x10\t\x12\x12\n" +
	"\x0eSEVERITY_INFO2\x10\n" +
	"\x12\x12\n" +
	"\x0eSEVERITY_INFO3\x10\v\x12\x12\n" +
	"\x0eSEVERITY_INFO4\x10\f\x12\x11\n" +
	"\rSEVERITY_WARN\x10\r\x12\x12\n" +
	"\x0eSEVERITY_WARN2\x10\x0e\x12\x12\n" +
	"\x0eSEVERITY_WARN3\x10\x0f\x12\x12\n" +
	"\x0eSEVERITY_WARN4\x10\x10\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x11\x12\x13\n" +
	"\x0fSEVERITY_ERROR2\x10\x12\x12\x13\n" +
	"\x0fSEVERITY_ERROR3\x10\x13\x12\x13\n" +
	"\x0fSEVERITY_ERROR4\x10\x14\x12\x12\n" +
	"\x0eSEVERITY_FATAL\x10\x15\x12\x13\n" +
	"\x0fSEVERITY_FATAL2\x10\x16\x12\x13\n" +
	"\x0fSEVERITY_FATAL3\x10\x17\x12\x13\n" +
	"\x0fSEVERITY_FATAL4\x10\x18*\xad\x01\n" +
	"\x0eWorkloadStatus\x12\x14\n" +
	"\x10WorkStatePending\x10\x00\x12\x14\n" +
	"\x10WorkStateRunning\x10\x01\x12\x16\n" +
	"\x12WorkStateSucceeded\x10\x02\x12\x13\n" +
	"\x0fWorkStateFailed\x10\x03\x12\x15\n" +
	"\x11WorkStateCanceled\x10\x04\x12\x15\n" +
	"\x11WorkStateReleased\x10\x05\x12\x14\n" +
	"\x10WorkStateUnknown\x10\x06B(Z&github.com/ansible/receptor/pkg/loggerb\x06proto3"

var (
	file_receptor_logs_proto_rawDescOnce sync.Once
	file_receptor_logs_proto_rawDescData []byte
)

func file_receptor_logs_proto_rawDescGZIP() []byte {
	file_receptor_logs_proto_rawDescOnce.Do(func() {
		file_receptor_logs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_receptor_logs_proto_rawDesc), len(file_receptor_logs_proto_rawDesc)))
	})
	return file_receptor_logs_proto_rawDescData
}

var file_receptor_logs_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_receptor_logs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_receptor_logs_proto_goTypes = []any{
	(SeverityNumber)(0),           // 0: logger.SeverityNumber
	(WorkloadStatus)(0),           // 1: logger.WorkloadStatus
	(*KeyValue)(nil),              // 2: logger.KeyValue
	(*ReceptorLogRecord)(nil),     // 3: logger.ReceptorLogRecord
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_receptor_logs_proto_depIdxs = []int32{
	0, // 0: logger.ReceptorLogRecord.severity_number:type_name -> logger.SeverityNumber
	4, // 1: logger.ReceptorLogRecord.time_unix_nano:type_name -> google.protobuf.Timestamp
	2, // 2: logger.ReceptorLogRecord.attributes:type_name -> logger.KeyValue
	1, // 3: logger.ReceptorLogRecord.status:type_name -> logger.WorkloadStatus
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_receptor_logs_proto_init() }
func file_receptor_logs_proto_init() {
	if File_receptor_logs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_receptor_logs_proto_rawDesc), len(file_receptor_logs_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_receptor_logs_proto_goTypes,
		DependencyIndexes: file_receptor_logs_proto_depIdxs,
		EnumInfos:         file_receptor_logs_proto_enumTypes,
		MessageInfos:      file_receptor_logs_proto_msgTypes,
	}.Build()
	File_receptor_logs_proto = out.File
	file_receptor_logs_proto_goTypes = nil
	file_receptor_logs_proto_depIdxs = nil
}
